/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmokko.utils.fastforms;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author psyriccio
 */
public class BusyForm extends javax.swing.JDialog {

    /**
     * Creates new form BusyForm
     */
    public BusyForm(javax.swing.JFrame parent, String title, String message) {
        initComponents();
        if(parent == null) {
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int locationX = (screenSize.width - getWidth()) / 2;
            int locationY = (screenSize.height - getHeight()) / 2;
            setBounds(locationX, locationY, getWidth(), getHeight());
        } else {
            Rectangle parentRect = parent.getBounds();
            int locationX = parentRect.x + (getWidth() / 2) - (getWidth() / 2 );  
            int locationY = parentRect.y + (getHeight() / 2) - (getHeight() / 2);
            setBounds(locationX, locationY, getWidth(), getHeight());
        }
        setTitle(title);
        jXBL.setText(message);
    }

    public void run(Runnable runnable) {
        setVisible(true);
        runnable.run();
        setVisible(false);
    }
    
    public void done() {
        setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXBL = new org.jdesktop.swingx.JXBusyLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setName("BusyForm"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jXBL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.SystemColor.windowBorder, java.awt.SystemColor.windowBorder, java.awt.SystemColor.windowText, java.awt.SystemColor.controlDkShadow));
        jXBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jXBL.setText("### ### ###");
        jXBL.setToolTipText("");
        jXBL.setBusy(true);
        jXBL.setDirection(org.jdesktop.swingx.painter.BusyPainter.Direction.RIGHT);
        jXBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXBL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXBL, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXBL, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXBusyLabel jXBL;
    // End of variables declaration//GEN-END:variables
}
